spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8028

logging:
  file:
    name: logs/dedalus.log
    path: dedalus
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























